### ISSUE TITLE
no issue / question of security implementation / link creation tracking

### ISSUE THREAD

**Issue by fsantiago07044** [aldakur/wp-polr#3]
Hello,

question; if i deploy this plugin on my site and assign it an api key from my account on my polr site, will all users of the wp site be using the same api key to shorten links or only from within my wp profile will this api key be usable? 

if it would be open to all of my wp site's user accounts, how can i track who has created what links? 

or would each wp user profile need to supply their own api key and polr site to use?

**Comment by aldakur** [comment]
Hi,

Now wp site use the same api key to all users. So, unfortunately you can't track who has created wht link because all link appear in the same polr account.

I'll try to develop new version to separate the users links.

**Comment by fsantiago07044** [comment]
thanks
