### ISSUE TITLE
Not working with latest Wordpress Version

### ISSUE THREAD

**Issue by snapcardster** [aldakur/wp-polr#4]
When I go to `wp-admin/options-general.php?page=polr ` there is just a blank page. I'd love to use your plugin. Any help?

![image](https://user-images.githubusercontent.com/39913990/46582130-ac2bbd00-ca42-11e8-909f-0d6459861ba1.png)

**Comment by aldakur** [comment]
What is your WP version? and what is the error on Debug mode?

**Comment by aldakur** [comment]
At this moment the plugin works with the latest version of Wordpress (5.5.3)
